"""
S-Class EOS V9.2 - Epistemic Truthfulness & 5D Gate Hardened Test Suite

Validates:
1. Missing/Fallback evidence MUST have quality 0.0 (EvidenceState.NO_EVIDENCE).
2. Synthetic fallback alternatives DO NOT count as explored.
3. Orthogonal 5D Challenge Protocol produces explicit PASS / FAIL / UNKNOWN statuses.
4. UNKNOWN high-risk dimensions or NO_EVIDENCE MUST NOT ACCEPT (returns INSUFFICIENT_DEBATE).
5. Strict Security Grounding requires actual ACTOR + CAPABILITY + AUTHORIZED_FOR edge.
6. Epistemic Invariant: Unknown is never equivalent to evidence, and absence of an objection is never proof of correctness.
"""

import os
import sys
import json
import pytest

PLUGIN_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PLUGIN_DIR not in sys.path:
    sys.path.insert(0, PLUGIN_DIR)

from domain_primitives import DomainPrimitiveType, DomainNode, SemanticDomainGraph
from behavior_graph import BehaviorGraphEngine, EpistemicStatus, BehaviorGraph
from requirement_ir import RequirementGraph, RequirementNode, RequirementKind, NFRCategory
from hld_compiler import HLDCompiler, HLDDesign, HLDModule, ADRRecord, ValidationStatus, ApprovalStatus
from artifact_governor import ArtifactGovernor, ApprovalRecord, ApprovalAuthority, FSMTransitionTarget
from architecture_debate import (
    ArchitectureDebateEngine,
    EngineeringClaim,
    ArchitecturalAlternative,
    ClaimChallenge,
    DecisionRecord,
    DebateResult,
    DecisionOutcome,
    EvidenceQualityRecord,
    EvidenceState,
    DimensionGateResult,
    ClaimDecomposer,
    GenericDebateEvaluator,
    DecisionSufficiencyGate
)
import runtime


def test_missing_evidence_must_have_quality_zero_and_reject_acceptance():
    """Adversarial Test 1: ADR with empty or fallback evidence MUST be assigned EvidenceState.NO_EVIDENCE and quality 0.0."""
    r_graph = RequirementGraph()
    b_graph = BehaviorGraph()
    adr = ADRRecord(
        id="ADR-001",
        title="Architectural Topology Selection",
        decision="Modular Monolith with Bounded Contexts",
        alternatives=[],
        evidence=["Default architectural inference"],  # Generic fallback!
        affected_modules=["mod_1"],
        rejected_options=[],
        reason="Default",
        status="PROPOSED",
        confidence=0.50,
        epistemic_status=EpistemicStatus.PROPOSED
    )

    claim = ClaimDecomposer.decompose_adr_to_claim(adr, r_graph, b_graph, raw_request="")

    assert len(claim.evidence_quality_records) == 1
    ev_rec = claim.evidence_quality_records[0]
    assert ev_rec.evidence_state == EvidenceState.NO_EVIDENCE
    assert ev_rec.quality_score == 0.0

    # Sufficiency Gate MUST return INSUFFICIENT_DEBATE, NOT ACCEPT!
    blast = {"blast_radius_score": 0.40}
    dim_gates = [
        DimensionGateResult("Scalability & Performance", "UNKNOWN", [], ["No throughput NFR"], []),
        DimensionGateResult("Security & Authorization", "UNKNOWN", [], ["No auth rules"], [])
    ]
    outcome, confidence, metrics = DecisionSufficiencyGate.evaluate_sufficiency(claim, [], [], blast, dim_gates)

    assert outcome == DecisionOutcome.INSUFFICIENT_DEBATE
    assert metrics["has_no_evidence"] is True
    assert metrics["gate_passed"] is False


def test_synthetic_fallback_alternatives_do_not_count_as_explored():
    """Adversarial Test 2: Synthetic alternatives generated by engine DO NOT satisfy alternatives_explored metric."""
    synth_alt = ArchitecturalAlternative("ALT-GEN-01", "Modular Monolith", "Generic fallback", [], [], 0.3, 0.5, is_synthetic=True)
    grounded_alt = ArchitecturalAlternative("ALT-REAL-01", "Kafka Streaming Microservices", "Grounded trade-off", ["Scale"], ["Complexity"], 0.8, 0.4, is_synthetic=False)

    ev_record = EvidenceQualityRecord("EV-1", EvidenceState.DIRECT_EVIDENCE, "REQUIREMENT_GRAPH", "Grounded requirement", 0.90, 1.0, 0.90, 0.90)
    claim = EngineeringClaim("CLAIM-1", "ADR-1", "Use Monolith", "Reason", [], [], [], [], [], [], [ev_record], "scale_throughput_invariant", 0.90)
    blast = {"blast_radius_score": 0.40}

    # Only synthetic alternatives provided -> alternatives_explored MUST BE FALSE!
    dim_gates_pass = [
        DimensionGateResult("Scalability & Performance", "PASS", ["Matched"], [], []),
        DimensionGateResult("Security & Authorization", "PASS", ["Matched"], [], [])
    ]
    outcome, confidence, metrics = DecisionSufficiencyGate.evaluate_sufficiency(claim, [], [synth_alt], blast, dim_gates_pass)

    assert metrics["grounded_alternatives_count"] == 0
    assert metrics["synthetic_alternatives_count"] == 1
    assert metrics["gate_passed"] is False
    assert outcome == DecisionOutcome.INSUFFICIENT_DEBATE

    # Grounded alternative provided -> alternatives_explored IS TRUE!
    outcome_g, confidence_g, metrics_g = DecisionSufficiencyGate.evaluate_sufficiency(claim, [], [grounded_alt], blast, dim_gates_pass)
    assert metrics_g["grounded_alternatives_count"] == 1
    assert outcome_g == DecisionOutcome.ACCEPT


def test_unknown_security_dimension_produces_unknown_not_pass():
    """Adversarial Test 3: Unstated security requirements produce UNKNOWN status, NEVER PASS."""
    r_graph = RequirementGraph()
    b_graph = BehaviorGraph()  # Empty graph: no actors, no capabilities, no auth edges!
    mod = HLDModule(id="mod_1", name="Core Context", system_boundary="internal", owned_entities=["Item"], owned_capabilities=["act"])

    adr_sec = ADRRecord("ADR-002", "Role Authorization Strategy", "RBAC with Epistemic Guards", [], ["Implicit"], ["mod_1"], [], "Security", "PROPOSED", 0.50, EpistemicStatus.PROPOSED)
    hld = HLDDesign(system_name="TestSys", architecture_style="Monolith", modules=[mod], adrs=[adr_sec])

    claim = ClaimDecomposer.decompose_adr_to_claim(adr_sec, r_graph, b_graph, raw_request="")
    challenges, alternatives, dim_gates = GenericDebateEvaluator.evaluate_5d_challenges(claim, adr_sec, hld, r_graph, b_graph, raw_request="")

    sec_gate = next(d for d in dim_gates if d.dimension_name == "Security & Authorization")
    assert sec_gate.status == "UNKNOWN"
    assert "Explicit role authorization policy rules" in sec_gate.missing_evidence


def test_orthogonal_5d_gate_protocol_populates_dimension_gates():
    """Verify GenericDebateEvaluator outputs 5 orthogonal dimension gates with PASS/FAIL/UNKNOWN statuses."""
    r_graph = RequirementGraph()
    b_graph = BehaviorGraph()
    mod = HLDModule(id="mod_1", name="Core Context", system_boundary="internal", owned_entities=["Item"], owned_capabilities=["act"])
    adr_1 = ADRRecord("ADR-001", "Topology Selection", "Modular Monolith", ["Microservices"], ["Valid"], ["mod_1"], [], "Reason", "ACCEPTED", 0.95, EpistemicStatus.CONFIRMED)
    hld = HLDDesign(system_name="TestSys", architecture_style="Monolith", modules=[mod], adrs=[adr_1])

    claim = ClaimDecomposer.decompose_adr_to_claim(adr_1, r_graph, b_graph, raw_request="Doctor approves prescription")
    challenges, alternatives, dim_gates = GenericDebateEvaluator.evaluate_5d_challenges(claim, adr_1, hld, r_graph, b_graph, raw_request="Doctor approves prescription")

    assert len(dim_gates) == 5
    gate_names = [d.dimension_name for d in dim_gates]
    assert "Scalability & Performance" in gate_names
    assert "Security & Authorization" in gate_names
    assert "Data Consistency & Persistence" in gate_names
    assert "Fault Tolerance & Resilience" in gate_names
    assert "Modularity & Coupling" in gate_names


def test_end_to_end_debate_no_evidence_blocks_acceptance(tmp_path):
    """Integration Test: Debate cycle with missing evidence returns INSUFFICIENT_DEBATE and blocks HMAC signing."""
    tmp_workspace = str(tmp_path)
    os.environ["SCLASS_EXECUTION_MODE"] = "TEST"

    r_graph = RequirementGraph()
    b_graph = BehaviorGraph()
    mod = HLDModule(id="mod_1", name="Core Context", system_boundary="internal", owned_entities=["Item"], owned_capabilities=["act"])
    
    # ADR with NO EVIDENCE
    adr_no_ev = ADRRecord("ADR-001", "Topology Selection", "Modular Monolith", [], [], ["mod_1"], [], "No evidence rationale", "PROPOSED", 0.50, EpistemicStatus.PROPOSED)
    hld = HLDDesign(system_name="HLD-001", architecture_style="Monolith", modules=[mod], adrs=[adr_no_ev])

    res = ArchitectureDebateEngine.run_debate_cycle(hld, r_graph, b_graph, raw_request="", workspace_dir=tmp_workspace)

    assert len(res.accepted_adrs) == 1
    assert res.accepted_adrs[0].status == "PROPOSED"  # MUST NOT BE ACCEPTED!
    assert res.decision_records[0].decision_outcome == DecisionOutcome.INSUFFICIENT_DEBATE

    # Verify NO HMAC approval record generated for ADR-001 in approvals.json
    verified_approvals = ArtifactGovernor._load_verified_approval_records(tmp_workspace)
    assert "ADR-001" not in verified_approvals
