"""
S-Class EOS V11.2 - D7 Agent Integration Models & Data Structures.
Defines immutable data classes for agent session context, turn responses, tool definitions,
and execution session records (§8.1, §8.3).
"""

from __future__ import annotations
import enum
from dataclasses import dataclass, field
from typing import Mapping, Optional, Sequence, Any, Tuple
from domain.models import _validate_pattern, _validate_iso8601, _freeze_nested
from domain.types import HEX_64_PATTERN


class AgentTurnStatus(str, enum.Enum):
    """Lifecycle status of a single agent session turn."""
    CONTINUE = "CONTINUE"
    PROPOSE_ACTION = "PROPOSE_ACTION"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    MAX_TURNS_REACHED = "MAX_TURNS_REACHED"


@dataclass(frozen=True)
class ToolDefinition:
    """Immutable definition of a capability-scoped tool exposed to an AI worker."""
    name: str
    description: str
    parameters_schema: Mapping[str, Any]
    required_capabilities: Tuple[str, ...] = field(default_factory=tuple)
    is_proposal_tool: bool = False

    def __post_init__(self):
        if not self.name or not isinstance(self.name, str):
            raise ValueError("Tool name must be a non-empty string.")
        if not self.description or not isinstance(self.description, str):
            raise ValueError("Tool description must be a non-empty string.")
        if not isinstance(self.parameters_schema, (dict, Mapping)):
            raise TypeError("parameters_schema must be a dictionary or Mapping.")
        object.__setattr__(self, "parameters_schema", _freeze_nested(self.parameters_schema))
        object.__setattr__(self, "required_capabilities", tuple(self.required_capabilities))


@dataclass(frozen=True)
class AgentToolCall:
    """Immutable record of a tool invocation emitted by an AI worker."""
    call_id: str
    tool_name: str
    arguments: Mapping[str, Any]

    def __post_init__(self):
        if not self.call_id or not isinstance(self.call_id, str):
            raise ValueError("call_id must be a non-empty string.")
        if not self.tool_name or not isinstance(self.tool_name, str):
            raise ValueError("tool_name must be a non-empty string.")
        object.__setattr__(self, "arguments", _freeze_nested(self.arguments))


@dataclass(frozen=True)
class AgentToolResult:
    """Immutable result of a tool execution fed back into agent context."""
    call_id: str
    tool_name: str
    success: bool
    result_data: Mapping[str, Any] = field(default_factory=dict)
    error_message: Optional[str] = None

    def __post_init__(self):
        if not self.call_id:
            raise ValueError("call_id cannot be empty.")
        if not self.tool_name:
            raise ValueError("tool_name cannot be empty.")
        object.__setattr__(self, "result_data", _freeze_nested(self.result_data))


@dataclass(frozen=True)
class AgentSessionContext:
    """Immutable context snapshot provided to the AI agent on each turn."""
    session_id: str
    task_id: str
    objective: str
    frontier_obligation_ids: Tuple[str, ...]
    frontier_details: Tuple[Mapping[str, Any], ...]
    policy_constraints: Tuple[str, ...]
    verification_feedback: Tuple[Mapping[str, Any], ...]
    available_tools: Tuple[ToolDefinition, ...]
    turn_index: int = 0
    max_turns: int = 10
    budget_remaining_usd: float = 10.0

    def __post_init__(self):
        if not self.session_id:
            raise ValueError("session_id cannot be empty.")
        if not self.task_id:
            raise ValueError("task_id cannot be empty.")
        if not self.objective:
            raise ValueError("objective cannot be empty.")
        if self.turn_index < 0:
            raise ValueError("turn_index cannot be negative.")
        if self.max_turns <= 0:
            raise ValueError("max_turns must be positive.")
        if self.budget_remaining_usd < 0.0:
            raise ValueError("budget_remaining_usd cannot be negative.")
        object.__setattr__(self, "frontier_obligation_ids", tuple(self.frontier_obligation_ids))
        object.__setattr__(self, "frontier_details", tuple(_freeze_nested(d) for d in self.frontier_details))
        object.__setattr__(self, "policy_constraints", tuple(self.policy_constraints))
        object.__setattr__(self, "verification_feedback", tuple(_freeze_nested(f) for f in self.verification_feedback))
        object.__setattr__(self, "available_tools", tuple(self.available_tools))


@dataclass(frozen=True)
class AgentTurnResponse:
    """Immutable response generated by an AI worker for a single turn."""
    thought: str
    tool_calls: Tuple[AgentToolCall, ...] = field(default_factory=tuple)
    turn_status: AgentTurnStatus = AgentTurnStatus.CONTINUE
    estimated_cost_usd: float = 0.0

    def __post_init__(self):
        if not isinstance(self.thought, str):
            raise TypeError("thought must be a string.")
        if not isinstance(self.turn_status, AgentTurnStatus):
            raise TypeError("turn_status must be an instance of AgentTurnStatus.")
        if self.estimated_cost_usd < 0.0:
            raise ValueError("estimated_cost_usd cannot be negative.")
        object.__setattr__(self, "tool_calls", tuple(self.tool_calls))


@dataclass(frozen=True)
class AgentSessionRecord:
    """Immutable audit record of a completed or terminated agent session."""
    session_id: str
    task_id: str
    total_turns: int
    total_cost_usd: float
    final_status: AgentTurnStatus
    started_at: str
    ended_at: str
    proposed_action_count: int
    turns_transcript: Tuple[Mapping[str, Any], ...] = field(default_factory=tuple)

    def __post_init__(self):
        if not self.session_id:
            raise ValueError("session_id cannot be empty.")
        if not self.task_id:
            raise ValueError("task_id cannot be empty.")
        if self.total_turns < 0:
            raise ValueError("total_turns cannot be negative.")
        if self.total_cost_usd < 0.0:
            raise ValueError("total_cost_usd cannot be negative.")
        _validate_iso8601(self.started_at, "started_at")
        _validate_iso8601(self.ended_at, "ended_at")
        if not isinstance(self.final_status, AgentTurnStatus):
            raise TypeError("final_status must be an instance of AgentTurnStatus.")
        object.__setattr__(self, "turns_transcript", tuple(_freeze_nested(t) for t in self.turns_transcript))
